### ISSUE TITLE
Simplify: Try to simplify the code when multiple selectors in the same section share style properties.

### ISSUE THREAD

**Issue by josephtkim** [mimiohashi/colmar#7]
https://github.com/mimiohashi/colmar/blob/master/resources/css/style.css#L6-L23

In this section, the h1, h2 and h4 elements share the font-weight property, which you can apply to them at once like so:

```css
h1, 
h2, 
h4 {
  font-weight: bold;
} 
```
